# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - clippyml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://clippy.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0d8097bc055e40eabcd99632c5bd1164 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_260108fb3b7247f98a0369189bfd4c4a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: clippy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0d8097bc055e40eabcd99632c5bd1164 }}/clippy/clippy/clippy-ml:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'clippyml'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d2734b114a0340038485999bbff4e839 }}
        images: 'clippy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0d8097bc055e40eabcd99632c5bd1164 }}/clippy/clippy/clippy-ml:${{ github.sha }}'